{% set provider = "Arukas" %}
{% set version = "1.0.0" %}

{% set name = "terraform-provider-" + provider.lower() %}
{% set x4_plugin = name + '_v' + version + "_x4" %}

{% set sha256 = "266f0f4fbc4b0fc01106ca99d27629dafade1c6f19a8c5e7f070752cffeceeee" %}
{% set sha256_win64 = "c6b03e3d5c6f19a9b88f1eeb8ccebbdbe45345090ef1d2f8bdd8bf00a8e912ad" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: src/github.com/terraform-providers/{{ name|lower }}
    url: https://github.com/terraform-providers/{{ name }}/archive/v{{ version }}.tar.gz  # [not win]
    sha256: {{ sha256 }}  # [not win]

    url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_windows_amd64.zip  # [win64]
    sha256: {{ sha256_win64 }}  # [win64]

build:
  number: 0
  script:
    - XCOPY src\github.com\terraform-providers\{{ name|lower }}\{{ x4_plugin }}.exe %LIBRARY_BIN%  # [win]

requirements:
  build:
    - {{ compiler('go') }}  # [not win]
    - make  # [not win]
  run:
    - terraform >=0.10

test:
  commands:
    - echo 'provider "{{ provider|lower }}" { version="{{ version }}" }' > init.tf  # [not win]
    - test $(terraform init | grep -c 'Downloading') = 0  # [not win]

about:
  home: https://www.terraform.io
  license: MPL 2.0
  summary: The Terraform {{ provider }} provider
  doc_url: https://www.terraform.io/docs/providers/{{ provider|lower }}/index.html
  dev_url: https://github.com/terraform-providers/{{ name }}

extra:
  recipe-maintainers:
    - sodre
