travis:
  secure:
    BINSTAR_TOKEN: FCyp4cV10X8CBXVfOtURWPxKK/L/jtSN2dOz0ZgzQColG7f7Gs8uha4oA9NKRAra9M1fWnxtn229oC6QdbvmXXzdWLaZf/d5CljWOG2zkf7fy+zRxFsc+ggun6QCbrJ8Uio9TdEmoNIjB7x3dBRpnShqMV4h171cWvGVEPab0xHJzM9YdSZbT4dUQ2JbnfbucchqgUypWAKoHIn3iILB7M9ROXFHfwazmRXhBC+8ay/FGbpAQIHLATnI/HD9D32fOOv1cIGKBPrQx4Sf/4vfKkPw25Yiq6MNNBOzWty6QB8f6a3uu31E5sCseY29f6L4l0A02A4JB730HHM9jsinkPbDm8k07JAGatBb/dBx+Nh6PRFK0tRVjsraPBPrXhLRYqRs7TShzUnZUTmjWUl0pE6zOtUAMoE321bz847nNohvG+J1EHinYK+OUCUdAfZtpDEOk4uyBxNq3L0MddNbnPtZyTSmUpbcEE2c7d0QC0rig4d9tD3oiXBHpkjAvJ1GUNOhBSdGnFatIFSvV+3OvwU/tMiNNskyBwVuwZ/2HV6/x/4qrhRCFNafDG+PLhBiMrRpnAZ0NN5Pv9xsxTvuITNtMNwJdEf6FgHOovGjGfWuul0bzfKtigYTV6aEL0JFt34UFVdKUiNxlmYMGIP/qOjxabocwjfNicbUwKtyGes=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
