travis:
  secure:
    BINSTAR_TOKEN: JqGveZgw6npiemehtcJ5L84LZ9YMlspBjgDPvLMSwW9uHT08tjZbF8pje6l5XxU0BjJk1S4g+UdGwQ+N1eW8efblDgox76CNV0QCns0NHWVcFahKCRRKw8BRSBh437KVOAkb/2I6yHp1oPFPnSC1i5s+bOpANfQf7p2ku6a0iCt/OpshlSke8ndnxqRrLFlVEUwLFimS0PbP+Zv38qjXPVeInr67hpjr71pQwWvqOktLJiZjGbSUpl10UP4DlsZ3cCzKj1aMHVUPg+bq9Pl3uomUXZtCzcz7N/owHaNML6uqPK1ulLPbECVQDMPdIS4l+dHhpSdWLMx/Zw2nLma81SdCe08r6icVSZMeLwlJQUEyhLIZGQMTJFHofHv4TaWh4Z80iLfPbIVlO/yosy59ovZCI27P/2wFxx6Oo0lZKii4lQVXxKbk7QcCYvHBi1zKQWLRtlLDrucwvoyqsnYQxDX/+2C5493evx0lg32O2GZgW5nnNZs69Efb6Hy8qp6t6np0U43SiD7BM/ruUUACGXpSYVcmS/KhYhHXdHwlweGJahhcBd2phMQqet5f2jSfCMRrx5IMuQ81KMSOd1G/hJZlpXyAZ42OTGn4UW2bMfDzgSXe/qbx2ajSh9jyJNeyefsse8GfOcrAO/HwMpaqPlx6fMy8CjPQW1KKvSqK0nc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
