travis:
  secure:
    BINSTAR_TOKEN: AxsjH6F3TUT5ASDZ2st/lFhaRY/X68BuCs2+9wliEOiO7GOlX8Cer3ZXv7nWbNbacJsBoaz/jZEVKROQOU3mVg1kOZqMRcuhO82QEDxgh0el0M+azP/KFBp8mQoG0JAlgd3GJkpBqP8QdC0YseE1l6PEBWjWahSpo+h7dYKJmX7cg0Q4ojsJKTS5pGmksnGVmRdi+o1NVSqRVZcoHFjXLkjPrbjWxx9m86iFpNaZo+lKK4fcq0QP/XGb4cFUnYY+dRts+hLVpOEttq0TeR8mP9fmlt5F7mfjiznE+vi1OdTsTgU4+Gzu5FeQHU9EDexL5sO+9pzCbKebktzVlGzJQ21eSv36dry1Kj46RPeLT0Xh3KKbRSrOI83UWMLnkObHWhdLOD1b/IBng7ve2rJo7pnaB1Z8QxdWJnmeNDYEobzVyaJ9XDmgoo3TE6DlhXw2huRGNjmSob30g/7qLeNUHkqc/6DzylUCunLYiZ/lEAtu0CJkSjddBLdTdko1DRUpLWmHzxPAp2WXHRwzWlJ+VFq9fQEXF+Ol0llzFb2w02rHHiS0/gKKYASp9Oty/Gk18huP4AOGRRrBFRNI2e8+ecXmykkpYM4rJBXzyox9Up+QXaAtIv3etHGIfIh0aRHA9G+50gdGNc6hYNLWn0ROLrrh6XzrDnrSEsVqGb9kj2s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
