travis:
  secure:
    BINSTAR_TOKEN: Yr6094cZfE3REcLY+4N5rXpYUVa4hQPvGBNOXs0TNQ+Z31OSNXBzYKE+yDFAklhisBqXXomZ3MXNJcNKa96xke1tqTfbaQoRmYNzsozUcl1xWsP+pVwwVSE9FTGappWeWIxGgDcH2zVY1Sz1QWDXzCIyQ/q1zPclYnCVMJK4KhZxB+736A/EfUBphMIiBeNhHfHuREQtmtmS+36h7DePFZjXK8TJRRZX5qBTXgScvfFbIhpEStQ8/fw699dzP+DgDYsuTQxBvacBwfDbkrAvvMXK3v28UeLi2Znup703LsUFetd1oxpBAK0P7eWgCjaTGWY8643A1lZzq4dWflPpKmyoJ9/G6tXsQzusN/ydqyjEqGNXxNJa2RMsXjOobmvLDmiOQJrjFRo2uDRR9/3Y82UfJGiV003XalNJt2KQIFbpr3WbZw5udDu0qDffy5Duhpz+okSs6iZxz1v1oAjoVezrti2znMX+x1KXyvtr1kUdAzRHkftv6z30Dfwz+oBZBUFBBbnspuvk4lwP6O93iXp6k7sjuYPIgVxtYu6XKEhH9k8rHTQiZJ5dTHr6PgTnX1jjCTwCy65tGV+kCByxgYDvb58vKraEak+wfvmP1QBZLsxw4Yt/22QXB9wuf88tYY6vusbVAtJ0oMaokcdJ8sVCJ4IxDDDg9s3j3iyHRKQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
