travis:
  secure:
    BINSTAR_TOKEN: BzdidoMaf7JFowR5Tf6FWRWDwQVioAp6+WCnOqlqNzFwAuFf3qdfTY+nJEuKW9CfTa47U2Y1OeJFrflcRmTxknh1zOI22SZbWCQqB8iLE1I4cVKNuRvfFjkUDi0K/1zPUTHDhSOCol/HgoC0d+oDzC1cPkdZ0QVU9sa09w2EuLCfe6BZl4HrPdVQaeYIHOJCy/CrJ4dq18NPo7COXaIpVebRE9mF/Mzz3kB0DLS3KweS4paeHRy+s5T9hdi6W8oEHZ5s8iP2p9/bgRhHQ/qJj82YyMA3Mcbz7x2yzLWlNI+14wTiNY/u4m+WBA7FKsZ13QebcC6FlQjNpYZAdY3WBM5QhDY3NGC7B44k0hQnr6F1hwzro7H+UsUyWtDbPUkrCbdRAHj4gr7ULTD5WKzzY+glKUTKGDherJ92b9gSXWNY0M2K0/HRFVvykZVC701By8ofilDYW6WA1QUQf7AmutE7wn/jD9gQFXZBybFo1PPFYAO4QM94m3GM0A0KUR7dROG7GFVKgQwEUTP7KRg36OXz+ec8nVbLH9TCPPZtw7Wm9ksM96AcNjK2AbjmMYlgVw82bpj9+P4DzebBQQ2raGz+lvYyKzGU54I3eg+IuPYRqy9TE+FW+ZVdQ8tuxQHvh28MWDGZjZX9y3mxvQkkasyXqqpDKTXnCIB5RqjVElU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
