travis:
  secure:
    BINSTAR_TOKEN: X1bQYNW8ihnY3ipAULyXuIi/F8YpADh9m1hzbLVV4hE+mJjDZd7zE5X5f8e4Gv8W6HL8v/z+ZP6xgOUWiERwK2FT5juWExTuBXAyrWuXmFMLCvgUVRKyOQOP7SjRjK9winnjG+/zh92OPO5k9Tg60P1ktffE8+s6dsiGL+kOqDyIh3U9EHjMAV3kCxo7zPraVPV/tQpClPgYfnPVu1/OAhO/kno1VQS5NpJaWNmVKWffTSEY07mk5fab4+T420dyVg4Mt++qIvew9hEkvuTwcZFVggziQeGElJw1TMm/eOasNak83CGDAQwQ+McXdyz62GOmXN+0gkIFRLamwOhUL+AK3mQECSDFwIQJPTj5YjDEyxFQtjF2Epf5qY5kpkKK2RQKc5sUQT/P+PhTX7tdhb9kg5e/ZII2v07rcFXwAdBKEirtr2CuWXgItlE0bIFxJH2L+ZrWwfL3MCtsjhIZnWHiMhJEpzM9TIDElmzPzJP0lfjqrpB9AT3z55SFQyejlRLQBdYLBm+z2U3xm7IDEBoKB+TtArWyM4VuVj6v4wrTw2Y4RASNlMZmNVlNg/4gu4zFKpPoi4q+UEq60wve47Iv6PedpZM0MkxbnNPfTExAKlXcGG3uQcR8V7NQ+Q0mVE3HypWkQ7MYZMETKY6o5H9lvi4CjBSoS/QVCmxPTiM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
